### ISSUE TITLE
Designer should still open remote project when user is not a valid user in DB

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-designer#24]
Currently, if a person discovers a remote project (MDW 6) and tries to expand it, if that user is not in the DB, the Rest call will throw an exception because the User service in MDW6 instance will return a 404 HTTP code, causing Designer to handle this as an error instead of opening with read-only permissions.   Project should still open and allow the user to look around.

Here's the stack trace from designer:

com.centurylink.mdw.dataaccess.DataAccessOfflineException: Unable to connect to http://tomwf-dev1.pcfomactl.dev.intranet:80/mdw
	at com.centurylink.mdw.designer.UserDataAccessRest.getUser(UserDataAccessRest.java:60)
	at com.centurylink.mdw.designer.DesignerDataAccess.getUser(DesignerDataAccess.java:1110)
	at com.centurylink.mdw.designer.display.DesignerDataModel.reloadPriviledges(DesignerDataModel.java:1189)
	at com.centurylink.mdw.designer.MainFrame.startSession(MainFrame.java:197)
	at com.centurylink.mdw.plugin.designer.DesignerProxy.initialize(DesignerProxy.java:342)
	at com.centurylink.mdw.plugin.project.model.WorkflowProject.initialize(WorkflowProject.java:731)
	at com.centurylink.mdw.plugin.designer.views.ProcessExplorerContentProvider$1.run(ProcessExplorerContentProvider.java:77)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.io.IOException: Unable to connect to http://tomwf-dev1.pcfomactl.dev.intranet:80/mdw
	at com.centurylink.mdw.designer.utils.RestfulServer.invokeResourceService(RestfulServer.java:287)
	at com.centurylink.mdw.designer.ServerAccessRest.invokeResourceService(ServerAccessRest.java:28)
	at com.centurylink.mdw.designer.UserDataAccessRest.getUser(UserDataAccessRest.java:52)
	... 7 more
Caused by: java.io.FileNotFoundException: http://tomwf-dev1.pcfomactl.dev.intranet:80/mdw/Services/User?format=json&cuid=jbrojde&withRoles=true
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at com.centurylink.mdw.common.utilities.HttpHelper.readInput(HttpHelper.java:208)
	at com.centurylink.mdw.common.utilities.HttpHelper.getBytes(HttpHelper.java:195)
	at com.centurylink.mdw.common.utilities.HttpHelper.get(HttpHelper.java:177)
	at com.centurylink.mdw.designer.utils.RestfulServer.invokeResourceService(RestfulServer.java:281)
	... 9 more

**Comment by naveena-bellamkonda** [comment]
This issue is not reproducible with the latest designer/RCP versions.
However, another issue is , designer is throwing exception "Extra/Archived packages not retrieved: http://tomwf-dev1.pcfomactl.dev.intranet:80/mdw/Services/Packages?format=json&nonVersioned=true" if webtools is  not installed (and property not set mdw.webtools.url) which is confusing error to the user. So this is changed to log the message instead of throwing the exception.
