### ISSUE TITLE
Designer error when trying to select Notice template in a Task template

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-designer#37]
When editing a task tamplate (.task asset file), click on Notices tab, then click on Template column for any notice outcome, select a template (i.e. mdw.base/taskOpenEmail.html), then you get an error "java.lang.StringIndexOutOfBoundsException: String index out of range: -1"

Here's the stack trace:

!ENTRY org.eclipse.jface 4 2 2017-11-02 09:05:01.154
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.centurylink.mdw.plugin.designer.editors.TaskTemplateEditor$NoticesValueChangeListener.attributeValueChanged(TaskTemplateEditor.java:578)
	at com.centurylink.mdw.plugin.designer.model.WorkflowAsset.fireAttributeValueChanged(WorkflowAsset.java:342)
	at com.centurylink.mdw.plugin.designer.model.TaskTemplate.setAttribute(TaskTemplate.java:162)
	at com.centurylink.mdw.plugin.designer.properties.editor.TableEditor$DefaultModelUpdater.updateModelValue(TableEditor.java:908)
	at com.centurylink.mdw.plugin.designer.properties.editor.TableEditor$DefaultCellModifier.modify(TableEditor.java:1101)
	at org.eclipse.jface.viewers.ColumnViewer$2.setValue(ColumnViewer.java:260)
	at org.eclipse.jface.viewers.EditingSupport.saveCellEditorValue(EditingSupport.java:113)
	at org.eclipse.jface.viewers.ColumnViewerEditor.saveEditorValue(ColumnViewerEditor.java:453)
	at org.eclipse.jface.viewers.ColumnViewerEditor.applyEditorValue(ColumnViewerEditor.java:309)
	at org.eclipse.jface.viewers.ColumnViewerEditor$1.applyEditorValue(ColumnViewerEditor.java:152)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:336)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:333)
	at com.centurylink.jface.viewers.TreeComboCellEditor.applyEditorValueAndDeactivate(TreeComboCellEditor.java:181)
	at com.centurylink.jface.viewers.TreeComboCellEditor$2.handleEvent(TreeComboCellEditor.java:93)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at com.centurylink.swt.widgets.CTreeCombo.listEvent(CTreeCombo.java:713)
	at com.centurylink.swt.widgets.CTreeCombo$2.handleEvent(CTreeCombo.java:92)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

!ENTRY org.eclipse.ui 4 0 2017-11-02 09:05:05.802
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.centurylink.mdw.plugin.designer.editors.TaskTemplateEditor$NoticesValueChangeListener.attributeValueChanged(TaskTemplateEditor.java:578)
	at com.centurylink.mdw.plugin.designer.model.WorkflowAsset.fireAttributeValueChanged(WorkflowAsset.java:342)
	at com.centurylink.mdw.plugin.designer.model.TaskTemplate.setAttribute(TaskTemplate.java:162)
	at com.centurylink.mdw.plugin.designer.properties.editor.TableEditor$DefaultModelUpdater.updateModelValue(TableEditor.java:908)
	at com.centurylink.mdw.plugin.designer.properties.editor.TableEditor$DefaultCellModifier.modify(TableEditor.java:1101)
	at org.eclipse.jface.viewers.ColumnViewer$2.setValue(ColumnViewer.java:260)
	at org.eclipse.jface.viewers.EditingSupport.saveCellEditorValue(EditingSupport.java:113)
	at org.eclipse.jface.viewers.ColumnViewerEditor.saveEditorValue(ColumnViewerEditor.java:453)
	at org.eclipse.jface.viewers.ColumnViewerEditor.applyEditorValue(ColumnViewerEditor.java:309)
	at org.eclipse.jface.viewers.ColumnViewerEditor$2.focusLost(ColumnViewerEditor.java:215)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:144)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at com.centurylink.swt.widgets.CTreeCombo.handleFocus(CTreeCombo.java:344)
	at com.centurylink.swt.widgets.CTreeCombo$3.handleEvent(CTreeCombo.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1270)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1078)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2934)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2437)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5446)
	at org.eclipse.swt.widgets.Canvas.WM_SETFOCUS(Canvas.java:485)
	at org.eclipse.swt.widgets.Decorations.WM_SETFOCUS(Decorations.java:1817)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4869)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1656)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2199)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:506)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1656)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2199)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.DestroyWindow(Native Method)
	at org.eclipse.swt.widgets.Control.destroyWidget(Control.java:795)
	at org.eclipse.swt.widgets.Shell.destroyWidget(Shell.java:719)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:846)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:460)
	at org.eclipse.swt.widgets.Decorations.dispose(Decorations.java:459)
	at org.eclipse.swt.widgets.Shell.dispose(Shell.java:737)
	at org.eclipse.jface.window.Window.close(Window.java:330)
	at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:989)
	at org.eclipse.ui.internal.statushandlers.InternalDialog.close(InternalDialog.java:700)
	at org.eclipse.jface.dialogs.Dialog.okPressed(Dialog.java:949)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:466)
	at org.eclipse.ui.internal.statushandlers.InternalDialog.buttonPressed(InternalDialog.java:193)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by naveena-bellamkonda** [comment]
This is already fixed and will be available with 9.1.8 build
