### ISSUE TITLE
Remove code formatting option from eclipse (MDW Tools) 

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw-designer#61]
Should we remove the code formatting option from eclipse (MDW Tools)  since we have a dependency on 143 and we have instructions in [format.md](https://github.com/CenturyLinkCloud/mdw/blob/master/docs/_docs/code/format.md)

java.net.UnknownHostException: lxdenvmtc143.dev.qintra.com
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.net.Socket.connect(Socket.java:589)
                at java.net.Socket.connect(Socket.java:538)
                at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
                at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
                at sun.net.www.http.HttpClient.New(HttpClient.java:308)
                at sun.net.www.http.HttpClient.New(HttpClient.java:326)
                at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
                at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
                at com.centurylink.mdw.plugin.workspace.WorkspaceConfigurator.loadPreferences(WorkspaceConfigurator.java:179)
                at com.centurylink.mdw.plugin.workspace.WorkspaceConfigurator.doConfigure(WorkspaceConfigurator.java:101)
                at com.centurylink.mdw.plugin.workspace.WorkspaceConfigurator.run(WorkspaceConfigurator.java:88)

**Comment by naveena-bellamkonda** [comment]
Instead of completely removing the option, can we check the connectivity of the workspace setup url and enable the option?

**Comment by magrawa** [comment]
Sure, that will work too.
