### ISSUE TITLE
Designer changes format of task template to XML when editing template

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-designer#74]
When task template is created, it is in JSON format, as it should be.  Then if you edit and save asset again, Designer will change it to XML, which the server cannot load and throws this exception:

[(s)20180420.11:17:02.183 ~88] A JSONObject text must begin with '{' at 1 [character 2 line 1]
com.centurylink.mdw.dataaccess.DataAccessException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.getTaskTemplates(LoaderPersisterVcs.java:1075)
	at com.centurylink.mdw.service.data.task.TaskTemplateCache.load(TaskTemplateCache.java:68)
	at com.centurylink.mdw.service.data.task.TaskTemplateCache.loadCache(TaskTemplateCache.java:62)
	at com.centurylink.mdw.service.data.task.TaskTemplateCache.refreshCache(TaskTemplateCache.java:83)
	at com.centurylink.mdw.services.cache.CacheRegistration.refreshCache(CacheRegistration.java:239)
	at com.centurylink.mdw.services.cache.CacheRegistration.refreshCaches(CacheRegistration.java:204)
	at com.centurylink.mdw.service.rest.WorkflowCache.post(WorkflowCache.java:85)
	at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:99)
	at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:59)
	at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:99)
	at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:408)
	at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:265)
	at com.centurylink.mdw.hub.servlet.RestServlet.doPost(RestServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:230)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:333)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1519)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1475)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:195)
	at org.json.JSONObject.<init>(JSONObject.java:319)
	at com.centurylink.mdw.model.JsonObject.<init>(JsonObject.java:34)
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.loadTaskTemplate(LoaderPersisterVcs.java:578)
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.loadTaskTemplates(LoaderPersisterVcs.java:686)
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.getTaskTemplates(LoaderPersisterVcs.java:1066)
	... 42 more

**Comment by jbrojdeCTL** [comment]
In file TaskTemplateEditor.java, it has this:

if ((pkgMeta != null && pkgMeta.trim().startsWith("{")) || taskTemplate.getPackage()
                        .getSchemaVersion() >= DataAccess.schemaVersion61) {
                    taskTemplate.setContent(taskTemplate.getTaskVO().getJson().toString(2));
 }
else {
                    TaskTemplateDocument doc = TaskTemplateDocument.Factory.newInstance();
                    doc.setTaskTemplate(taskTemplate.getTaskVO().toTemplate());
                    XmlOptions xmlOptions = new XmlOptions().setSaveAggressiveNamespaces();
                    xmlOptions.setSavePrettyPrint().setSavePrettyPrintIndent(2);
                    taskTemplate.setContent(doc.xmlText(xmlOptions));  
}

This is not working properly to identify the right version.   Depends on how the package info is loaded by Designer, I suspect that getSchemaVersion() return 6.1 instead of 6001.

**Comment by jbrojdeCTL** [comment]
This is a duplicate of issue # 69
