### ISSUE TITLE
Errors when importing mdw gradle-based project on Windows

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-designer#76]
Start with any workspace and select File > Import > Existing Projects into Workspace.  Browse for mdw-demo and click Finish.  An error dialog is displayed and the stack trace below appears in the workspace log.  Restarting Eclipse clears up this error, and correctly displays Project and External Dependencies.

If mdw-demo/.settings/org.eclipse.buildship.core.prefs is deleted prior to import, no error is displayed but Project and External Dependencies are missing.  This is probably not strictly a Designer issue, but it would be nice if we could handle it.  It would be best if we don't tell users they have to import existing Gradle project.  Maybe "Import Existing MDW Project" to handle this?

```
!ENTRY org.eclipse.buildship.core 4 0 2018-04-25 12:24:06.989
!MESSAGE Synchronize Gradle projects with workspace failed due to an error configuring Eclipse.
!STACK 0
org.eclipse.buildship.core.GradlePluginsRuntimeException: Cannot store preferences in project mdw-demo in node org.eclipse.buildship.core.
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$ProjectScopeEclipsePreferencesPreferenceStore.flush(PreferenceStore.java:153)
	at org.eclipse.buildship.core.configuration.internal.BuildConfigurationPersistence.saveRootDirPreference(BuildConfigurationPersistence.java:160)
	at org.eclipse.buildship.core.configuration.internal.BuildConfigurationPersistence.savePathToRoot(BuildConfigurationPersistence.java:90)
	at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.saveProjectConfiguration(DefaultConfigurationManager.java:140)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:175)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:134)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:131)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.osgi.service.prefs.BackingStoreException: Exception occurred while saving project preferences: /mdw-demo/.settings/org.eclipse.buildship.core.prefs.
	at org.eclipse.core.internal.resources.ProjectPreferences.save(ProjectPreferences.java:670)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalFlush(EclipsePreferences.java:431)
	at org.eclipse.core.internal.resources.ProjectPreferences.flush(ProjectPreferences.java:365)
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$ProjectScopeEclipsePreferencesPreferenceStore.flush(PreferenceStore.java:151)
	... 16 more
```

**Comment by donaldoakes** [comment]
Seems this is already fixed in Eclipse 4.8:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=522214
